export const SET_RESTAURANTS = "REST/SET_RESTAURANTS";
export const SET_LOADING = "LOADING/SET_LOADING";
export const SET_LOADED = "LOADED/SET_LOADED";
export const SET_MESSAGE = "MESSAGE/SET_MESSAGE";
export const SET_RESTAURANT_INFO = "SET_RESTAURANT_INFO"
export const DELETE_RESTAURANT_INFO = "DELETE_RESTAURANT_INFO"
